package com.example.easyrecipes.data;

import com.example.easyrecipes.EasyRecipes;
import com.example.easyrecipes.script.CraftingScriptGenerator;
import com.example.easyrecipes.script.RecipeScriptGenerator;
import net.minecraftforge.fml.loading.FMLPaths;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Source of truth for editor-managed recipes, living in the game folder of whoever runs it — which
 * is now always the <em>server</em> (the integrated one in single-player). The manifest (JSON) is
 * authoritative; the KubeJS script is fully regenerated from it on every change so that removing a
 * recipe is possible.
 */
public final class RecipeStore {

    private static final String SCRIPT_HEADER =
            "// Generated by Easy Recipes — managed by the /easyrecipes editor. Do not edit by hand." + "\n";

    private RecipeStore() {}

    private static Path manifest() {
        return FMLPaths.GAMEDIR.get().resolve("config").resolve("easyrecipes").resolve("recipes.json");
    }

    private static Path script() {
        return FMLPaths.GAMEDIR.get().resolve("kubejs").resolve("server_scripts").resolve("easyrecipes_generated.js");
    }

    /**
     * Loads all saved recipes; empty (mutable) list if none exist or on read error. Entries missing
     * an id get one assigned and persisted, so ids stay stable across loads (the client references
     * entries by id when removing).
     */
    public static List<RecipeEntry> load() {
        Path path = manifest();
        if (!Files.exists(path)) {
            return new ArrayList<>();
        }
        List<RecipeEntry> entries;
        try {
            entries = RecipeJson.listFromJson(Files.readString(path, StandardCharsets.UTF_8));
        } catch (Exception e) {
            // A corrupt manifest must be moved aside, not silently treated as empty: the next save
            // would overwrite it with just the new entry, erasing every recipe the user ever made.
            // Set aside, the recipes stay recoverable by hand.
            EasyRecipes.LOGGER.error("Recipe manifest is unreadable, setting it aside", e);
            try {
                Files.move(path, path.resolveSibling("recipes.json.corrupt-" + System.currentTimeMillis()));
            } catch (IOException moveFailed) {
                EasyRecipes.LOGGER.error("Could not set the corrupt manifest aside", moveFailed);
            }
            return new ArrayList<>();
        }

        boolean migrated = false;
        for (RecipeEntry entry : entries) {
            if (entry.id == null || entry.id.isBlank()) {
                entry.id = UUID.randomUUID().toString();
                migrated = true;
            }
            migrated |= migrateIds(entry);
        }
        if (migrated) {
            try {
                writeManifest(entries);
            } catch (IOException ignored) {
                // Ids stay in memory for this load; the next successful save persists them.
            }
        }
        return entries;
    }

    /** Rewrites every id field of an entry into the current format. True when something changed. */
    private static boolean migrateIds(RecipeEntry entry) {
        boolean changed = false;
        String[] singles = {entry.output, entry.input, entry.heldItem, entry.template, entry.base, entry.addition};
        String[] fixed = new String[singles.length];
        for (int i = 0; i < singles.length; i++) {
            fixed[i] = CraftingScriptGenerator.migrateLegacy(singles[i]);
            changed |= !Objects.equals(fixed[i], singles[i]);
        }
        entry.output = fixed[0];
        entry.input = fixed[1];
        entry.heldItem = fixed[2];
        entry.template = fixed[3];
        entry.base = fixed[4];
        entry.addition = fixed[5];

        if (entry.grid != null) {
            for (int i = 0; i < entry.grid.length; i++) {
                String migratedCell = CraftingScriptGenerator.migrateLegacy(entry.grid[i]);
                changed |= !Objects.equals(migratedCell, entry.grid[i]);
                entry.grid[i] = migratedCell;
            }
        }
        if (entry.itemInputs != null) {
            for (int i = 0; i < entry.itemInputs.size(); i++) {
                String migratedInput = CraftingScriptGenerator.migrateLegacy(entry.itemInputs.get(i));
                changed |= !Objects.equals(migratedInput, entry.itemInputs.get(i));
                entry.itemInputs.set(i, migratedInput);
            }
        }
        if (entry.createOutputs != null) {
            for (RecipeEntry.CreateOutput out : entry.createOutputs) {
                String migratedOut = CraftingScriptGenerator.migrateLegacy(out.id);
                changed |= !Objects.equals(migratedOut, out.id);
                out.id = migratedOut;
            }
        }
        return changed;
    }

    private static void writeManifest(List<RecipeEntry> entries) throws IOException {
        Path path = manifest();
        Files.createDirectories(path.getParent());
        Files.writeString(path, RecipeJson.listToJson(entries), StandardCharsets.UTF_8);
    }

    /** Persists the manifest and regenerates the KubeJS script from the full list. */
    public static void saveAndRegenerate(List<RecipeEntry> entries) throws IOException {
        writeManifest(entries);

        StringBuilder script = new StringBuilder(SCRIPT_HEADER);
        for (RecipeEntry entry : entries) {
            try {
                script.append('\n').append(RecipeScriptGenerator.generate(entry)).append('\n');
            } catch (Exception e) {
                // Rhino aborts the whole file on one bad line, so a single unusable entry must not
                // take every other recipe down with it. Skip it and keep going.
                EasyRecipes.LOGGER.error("Skipping unusable recipe '{}' ({}): {}",
                        entry.name, entry.id, e.getMessage());
            }
        }

        Path scriptPath = script();
        Files.createDirectories(scriptPath.getParent());
        Files.writeString(scriptPath, script.toString(), StandardCharsets.UTF_8);
    }
}
